#!/usr/bin/env bash
# ============================================================================
# run_sim.sh  -  Build and run the Solvyr-3 testbenches with Icarus Verilog.
#
# Requires: iverilog + vvp   (e.g. apt-get install iverilog)
#
# Usage:  ./run_sim.sh [target]
#   prim     alu/regfile/imm/decoder/control/lsu/branch/forward/hazard units
#   system   full integer-pipeline system test (forwarding/load-use/branch/mem)
#   csr      machine-mode trap test (ECALL + MRET round trip)
#   irq      timer-interrupt test (asynchronous trap entry)
#   gpio     GPIO integration test (CPU -> interconnect -> GPIO)
#   timer    timer compare-match + interrupt unit test
#   uart     UART loopback unit test
#   accel    DIR accelerator 2D-convolution self-check
#   all      run everything (default)
#
# Test programs (tb/*.hex) are generated by tools/rv32i.py.
# ============================================================================
set -e
cd "$(dirname "$0")"

# Core + memory + control RTL (integer pipeline)
CORE="rtl/alu.v rtl/regfile.v rtl/imm_gen.v rtl/decoder.v rtl/control_unit.v \
      rtl/forwarding_unit.v rtl/hazard_unit.v rtl/branch_unit.v \
      rtl/load_store_unit.v rtl/pipeline_regs.v rtl/csr_file.v \
      rtl/imem_bram.v rtl/dmem_bram.v rtl/solvyr3_core.v"

# Peripherals + accelerator + interconnect
SOC="$CORE rtl/mm_interconnect.v rtl/gpio.v rtl/timer.v \
     rtl/uart_rx_core.v rtl/uart.v \
     rtl/dsp_mac.v rtl/dpram_be.v rtl/dir_accel.v rtl/prog_loader.v \
     rtl/solvyr3_soc.v"

PRIM_RTL="rtl/alu.v rtl/regfile.v rtl/imm_gen.v rtl/decoder.v rtl/control_unit.v \
          rtl/load_store_unit.v rtl/branch_unit.v rtl/forwarding_unit.v rtl/hazard_unit.v"

IV="iverilog -g2012 -I rtl"

build_run () { # <name> <tb> <srcs...>
    local name=$1; shift; local tb=$1; shift
    echo "=== build $name ==="
    $IV -o "build_$name" "$tb" "$@"
    echo "=== run $name ==="
    vvp "build_$name"
    echo
}

gen_hex () {
    if command -v python3 >/dev/null 2>&1; then
        echo "=== regenerating test programs (tools/rv32i.py) ==="
        python3 tools/rv32i.py    >/dev/null 2>&1 || true
        python3 tools/gen_bench.py >/dev/null 2>&1 || true
    fi
}

gen_bench_c () {
    # Rebuild the C benchmark image so the simulation runs the SAME firmware as
    # the board. Falls back to the checked-in hex if no toolchain is installed.
    local p
    for p in riscv64-unknown-elf- riscv32-unknown-elf- riscv-none-elf-; do
        if command -v "${p}gcc" >/dev/null 2>&1; then
            echo "=== building bench/bench_c.hex (CROSS=$p) ==="
            make -s -C bench bench_c.hex CROSS="$p" && return 0
            echo "WARNING: bench_c.hex build failed; using the checked-in image"
            return 0
        fi
    done
    echo "WARNING: no RISC-V toolchain found -- using the checked-in bench/bench_c.hex."
    echo "         Rebuild it (make -C bench) after editing bench/bench.c so sim == board."
}

case "${1:-all}" in
    prim)   build_run prim   tb/tb_primitives.v $PRIM_RTL ;;
    system) gen_hex; build_run system tb/tb_system.v    $SOC ;;
    csr)    gen_hex; build_run csr    tb/tb_csr.v       $SOC ;;
    irq)    gen_hex; build_run irq    tb/tb_irq.v       $SOC ;;
    gpio)   gen_hex; build_run gpio   tb/tb_gpio.v      $SOC ;;
    timer)  build_run timer  tb/tb_timer.v     rtl/timer.v ;;
    uart)   build_run uart   tb/tb_uart.v      rtl/uart.v rtl/uart_rx_core.v ;;
    accel)  build_run accel  tb/tb_dir_accel.v rtl/dir_accel.v rtl/dsp_mac.v rtl/dpram_be.v ;;
    bench)  gen_bench_c; build_run bench bench/tb_bench.v $SOC ;;
    all)
        gen_hex
        build_run prim   tb/tb_primitives.v $PRIM_RTL
        build_run system tb/tb_system.v     $SOC
        build_run csr    tb/tb_csr.v        $SOC
        build_run irq    tb/tb_irq.v        $SOC
        build_run gpio   tb/tb_gpio.v       $SOC
        build_run timer  tb/tb_timer.v      rtl/timer.v
        build_run uart   tb/tb_uart.v       rtl/uart.v rtl/uart_rx_core.v
        build_run accel  tb/tb_dir_accel.v  rtl/dir_accel.v rtl/dsp_mac.v rtl/dpram_be.v
        gen_bench_c
        build_run bench  bench/tb_bench.v   $SOC
        echo "=== all testbenches built and run ==="
        ;;
    *) echo "usage: $0 {prim|system|csr|irq|gpio|timer|uart|accel|bench|all}"; exit 1 ;;
esac
